# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: ''  # the subpath of your site, e.g. /blog
exclude: ['README.md']
permalink: pretty

title: OpenSFT
email: hello@opensft.org
description: Bridging the worlds of open source technology and fashion & textiles by providing you with resources and 
  training.
url: "https://www.opensft.org" # the base hostname & protocol for your site
instagram_username: opensourceft
twitter_username: opensourceft
github_username:  opensourceft
google_analytics_id: "G-9WS3JV03MY"
footer:
  copyright_text: 'Copyright ©2022 Open Source Fashion & Textiles'

include: [_site]
keep_files:
  - _site/_redirects

seo:
  meta_og_title: "Open Source Fashion & Textiles"
  meta_og_type: "website"
  meta_og_url: "https://www.opensft.org"
  meta_og_image: ""
  meta_og_description: "Bridging the worlds of open source technology and fashion & textiles by providing you with resources and 
  training."
  meta_twitter_card: "summary"
  meta_twitter_site: "@opensourceft"
  meta_twitter_creator: "@opensourceft"

# Build settings
markdown: kramdown


gems:
  - jekyll-compose
  - jekyll-paginate

paginate: 6
paginate_path: "blog/page:num"

plugins:
  - jekyll-paginate
  - jekyll-environment-variables
  - jekyll-sitemap
